import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

interface AnalysisData {
  id: string;
  date: string;
  imageName: string;
  result: string;
  confidence: number;
  region: string;
  modality: string;
  findings: string[];
  differentialDiagnosis: { condition: string; probability: number }[];
}

export async function generateAnalysisPDF(analysis: AnalysisData, imageUrl?: string): Promise<void> {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let yPosition = 15;

  // Header
  pdf.setFillColor(0, 102, 204);
  pdf.rect(0, 0, pageWidth, 30, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.text('MedAIx', pageWidth / 2, 15, { align: 'center' });
  pdf.setFontSize(10);
  pdf.text('Medical Image Analysis Report', pageWidth / 2, 23, { align: 'center' });

  pdf.setTextColor(0, 0, 0);
  yPosition = 35;

  // Report Info
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Report Information', 15, yPosition);
  yPosition += 8;

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  const reportInfo = [
    `Report ID: ${analysis.id}`,
    `Analysis Date: ${new Date(analysis.date).toLocaleDateString()}`,
    `Image Name: ${analysis.imageName}`,
    `Modality: ${analysis.modality}`,
    `Region Analyzed: ${analysis.region}`,
  ];

  reportInfo.forEach((info) => {
    pdf.text(info, 15, yPosition);
    yPosition += 6;
  });

  // Image
  if (imageUrl) {
    yPosition += 5;
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Original Medical Image', 15, yPosition);
    yPosition += 10;

    try {
      pdf.addImage(imageUrl, 'JPEG', 15, yPosition, 180, 120);
      yPosition += 125;
    } catch (error) {
      console.error('Error adding image to PDF:', error);
    }
  }

  // Results Section
  if (yPosition > pageHeight - 80) {
    pdf.addPage();
    yPosition = 15;
  }

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Analysis Results', 15, yPosition);
  yPosition += 8;

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Primary Finding: ${analysis.result}`, 15, yPosition);
  yPosition += 6;

  // Confidence Score
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Confidence Score', 15, yPosition);
  yPosition += 6;

  pdf.setFont('helvetica', 'normal');
  const confidence = Math.round(analysis.confidence);
  pdf.setFillColor(0, 170, 0);
  pdf.rect(15, yPosition, (confidence / 100) * 100, 6, 'F');
  pdf.setDrawColor(200, 200, 200);
  pdf.rect(15, yPosition, 100, 6);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`${confidence}%`, 120, yPosition + 4);
  yPosition += 12;

  // Findings
  if (analysis.findings.length > 0) {
    pdf.setFont('helvetica', 'bold');
    pdf.text('Key Findings', 15, yPosition);
    yPosition += 6;

    pdf.setFont('helvetica', 'normal');
    analysis.findings.forEach((finding) => {
      const lines = pdf.splitTextToSize(finding, 180);
      lines.forEach((line: string) => {
        pdf.text(`• ${line}`, 15, yPosition);
        yPosition += 5;
      });
    });
    yPosition += 2;
  }

  // Differential Diagnosis
  if (yPosition > pageHeight - 60) {
    pdf.addPage();
    yPosition = 15;
  }

  if (analysis.differentialDiagnosis && analysis.differentialDiagnosis.length > 0) {
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Differential Diagnosis', 15, yPosition);
    yPosition += 6;

    pdf.setFont('helvetica', 'normal');
    analysis.differentialDiagnosis.forEach((diagnosis, idx) => {
      const prob = Math.round(diagnosis.probability);
      pdf.text(`${idx + 1}. ${diagnosis.condition}`, 15, yPosition);
      yPosition += 5;

      // Probability bar
      pdf.setFillColor(100, 150, 255);
      pdf.rect(20, yPosition, (prob / 100) * 80, 4, 'F');
      pdf.setDrawColor(200, 200, 200);
      pdf.rect(20, yPosition, 80, 4);
      pdf.setFontSize(8);
      pdf.text(`${prob}%`, 105, yPosition + 3);
      pdf.setFontSize(10);
      yPosition += 8;
    });
  }

  // Disclaimer
  if (yPosition > pageHeight - 40) {
    pdf.addPage();
    yPosition = 15;
  }

  yPosition += 5;
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(200, 100, 0);
  pdf.text('DISCLAIMER', 15, yPosition);
  yPosition += 6;

  pdf.setTextColor(0, 0, 0);
  pdf.setFont('helvetica', 'normal');
  const disclaimerText =
    'This analysis is generated by an AI model for research and educational purposes only. It is NOT a clinical diagnosis and should NOT be used as a substitute for professional medical advice, diagnosis, or treatment. Always consult with qualified healthcare professionals for medical decisions.';

  const disclaimerLines = pdf.splitTextToSize(disclaimerText, 180);
  disclaimerLines.forEach((line: string) => {
    pdf.text(line, 15, yPosition);
    yPosition += 5;
  });

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  const footerText = `Generated by MedAIx on ${new Date().toLocaleString()} | Report ID: ${analysis.id}`;
  pdf.text(footerText, pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save PDF
  pdf.save(`MedAIx_Analysis_${analysis.id}.pdf`);
}

export async function generatePDFFromElement(elementId: string, filename: string): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error(`Element with id "${elementId}" not found`);
    return;
  }

  try {
    const canvas = await html2canvas(element, {
      backgroundColor: '#ffffff',
      scale: 2,
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: canvas.width > canvas.height ? 'landscape' : 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const imgWidth = pdf.internal.pageSize.getWidth() - 20;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    pdf.addImage(imgData, 'PNG', 10, 10, imgWidth, imgHeight);
    pdf.save(filename);
  } catch (error) {
    console.error('Error generating PDF:', error);
  }
}

export async function downloadDataAsJSON(data: any, filename: string): Promise<void> {
  const jsonString = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
