-- AlterTable
ALTER TABLE "users" ADD COLUMN     "isPro" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "tokenLastResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "tokensTotal" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "tokensUsedToday" INTEGER NOT NULL DEFAULT 0;
